### ISSUE TITLE
undefined method unix

### ISSUE THREAD

**Issue by webmagnets** [railsjazz/rails_live_reload#19]
I'm on windows 11 (not sure if that matters). I'm getting this error in the server development log:

```
=> Run `bin/rails server --help` for more startup options
Watching: C:/Users/Local Admin/RubymineProjects/mess
  (?-mix:app\/views\/.+\.(erb|haml|slim)$) => on_change
  (?-mix:(app|vendor)\/(assets|javascript)\/\w+\/(.+\.(css|js|html|png|jpg|ts|jsx)).*) => always
#<Thread:0x00000202d8138030 C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rails_live_reload-0.3.1/lib/rails_live_reload/watcher.rb:59 run> terminated with exception (report_on_exception is true):
C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:1116:in `unix_server_socket': undefined method `unix' for Addrinfo:Class (NoMethodError)

    s = Addrinfo.unix(path).listen
                ^^^^^
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rails_live_reload-0.3.1/lib/rails_live_reload/watcher.rb:60:in `block in start_socket'
*** SIGUSR2 not implemented, signal based restart unavailable!
```

Any advice?

**Comment by igorkasyanchuk** [comment]
Please early version of the gem: https://rubygems.org/gems/rails_live_reload
Maybe 0.1.2.

Currently, we do not support Windows.
And I really suggest you switch to Linux, Mac, or Windows (but something like https://www.omgubuntu.co.uk/how-to-install-wsl2-on-windows-10, long term you anyway need to stop coding on Windows natively and as sooner you switch - better for you)

**Comment by webmagnets** [comment]
Thank you. I appreciate your advice.
